### ISSUE TITLE
Error on install (5.1.0.1)

### ISSUE THREAD

**Issue by AC1DFOX** [kingjacob280/BuildTools#11]
<img width="404" alt="Install Error" src="https://user-images.githubusercontent.com/75289053/100690595-777ace00-334c-11eb-9b00-358e22f895c4.PNG">

**Comment by kingjacob280** [comment]
Hi 

Is it possible to drag the message box from behind the loading Window?

If not and also helpful anyway, could you please post a copy of your log file (found under the Build Tools folder)

Thanks,
Jacob

**Comment by JacobMS2020** [comment]
> <img width="404" alt="Install Error" src="https://user-images.githubusercontent.com/75289053/100690595-777ace00-334c-11eb-9b00-358e22f895c4.PNG">
> 

Hi 

Is it possible to drag the message box from behind the loading Window?

If not and also helpful anyway, could you please post a copy of your log file (found under the Build Tools folder)

In the meantime I will try to recreate the error.

Thanks,
Jacob

**Comment by JacobMS2020** [comment]
The overlap issue has been fixed in the next version update.
This warning message was because you have not downloaded the full content of the program and it is missing needed files to run correctly.
Note the program will still run fine without these files but some features will not work.
