### ISSUE TITLE
Errors on Install

### ISSUE THREAD

**Issue by AC1DFOX** [kingjacob280/BuildTools#13]
I tried on a different system, (my laptop, Win10Pro), and received the following message trying to run the 5.1.0.2.exe. In addition following up on the response from the last issue submitted, I tried downloading the Archive instead of the .exe file, rendered sme exact issue. Attached are screenshots. 
![install](https://user-images.githubusercontent.com/75289053/100788520-cec77f80-33da-11eb-89bd-b37417538663.PNG)
![Add Installers](https://user-images.githubusercontent.com/75289053/100788521-cf601600-33da-11eb-9e8f-0035a777437a.PNG)
![From extracted Zip](https://user-images.githubusercontent.com/75289053/100788523-cf601600-33da-11eb-8833-8a6f94cf9a74.PNG)

**Comment by JacobMS2020** [comment]
Hi

Thank you for submitting your bug report. I am sorry this is not working for you.

If you navigate to the Build Tools folder (located in the same directory at the program), inside this folder should be a folder called installers and another one called other. In the installers folders should be some pre selected .exe programs like Google chrome setup. Exe.

Could you please confirm you can see these folders?

Also in the build tools folder you will find a log.log file that has a debugging report of what the program is doing in behind the scenes, posting this would also be helpful.

Let me know if you can find those folders.

Further to this a new release (5.1.0.2) has been created and is ready for download. 

https://github.com/kingjacob280/BuildTools/releases/tag/5.1.0.2

Kind regards,
Jacob
